apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'telegram'

receivers:
 - name: 'telegram'
  webhook_configs:
  - url: 'https://api.telegram.org/bot7208954720:AAE8Al5px1vySbT51sZce5mIkyPQGsxzmoo/sendMessage'
    send_resolved: true
    http_config:
      headers:
        Content-Type: 'application/json'
    template: |
      {
        "chat_id": "6754368173",
        "text": "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      }