apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
route:
  - match:
      severity: NodeCPUHighUsage
    receiver: telegram

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: 7208954720:AAE8Al5px1vySbT51sZce5mIkyPQGsxzmoo
    api_url: https://api.telegram.org
    chat_id: 6754368173
    parse_mode: ''