apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: default
  source:
    repoURL: apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/samsoe01/monitoring
    path: charts/kube-prometheus-stack
    targetRevision: main
    # Optional: Provide authentication credentials
     username: samsoe01
     password: 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
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true